# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/SeaGateTransferTemp/Sampler_Characterization/Sampler_Characterization.srcs/sources_1/bd/Sampler_Characterization/ip/Sampler_Characterization_processing_system7_0_0/Sampler_Characterization_processing_system7_0_0.xci
# IP: The module: 'Sampler_Characterization_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SeaGateTransferTemp/Sampler_Characterization/Sampler_Characterization.srcs/sources_1/bd/Sampler_Characterization/ip/Sampler_Characterization_processing_system7_0_0/Sampler_Characterization_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sampler_Characterization_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/SeaGateTransferTemp/Sampler_Characterization/Sampler_Characterization.srcs/sources_1/bd/Sampler_Characterization/ip/Sampler_Characterization_processing_system7_0_0/Sampler_Characterization_processing_system7_0_0.xci
# IP: The module: 'Sampler_Characterization_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SeaGateTransferTemp/Sampler_Characterization/Sampler_Characterization.srcs/sources_1/bd/Sampler_Characterization/ip/Sampler_Characterization_processing_system7_0_0/Sampler_Characterization_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sampler_Characterization_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
