# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/Injector_Characterization/Injector_Characterization.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Injector_Characterization || ORIG_REF_NAME==Injector_Characterization} -quiet] -quiet

# IP: bd/Injector_Characterization/ip/Injector_Characterization_vio_0_0/Injector_Characterization_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Injector_Characterization_vio_0_0 || ORIG_REF_NAME==Injector_Characterization_vio_0_0} -quiet] -quiet

# IP: bd/Injector_Characterization/ip/Injector_Characterization_clk_wiz_0/Injector_Characterization_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Injector_Characterization_clk_wiz_0 || ORIG_REF_NAME==Injector_Characterization_clk_wiz_0} -quiet] -quiet

# IP: bd/Injector_Characterization/ip/Injector_Characterization_util_reduced_logic_0_0/Injector_Characterization_util_reduced_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Injector_Characterization_util_reduced_logic_0_0 || ORIG_REF_NAME==Injector_Characterization_util_reduced_logic_0_0} -quiet] -quiet

# XDC: bd/Injector_Characterization/Injector_Characterization_ooc.xdc
