# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/ILA_Characterization/ILA_Characterization.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Characterization || ORIG_REF_NAME==ILA_Characterization} -quiet] -quiet

# IP: bd/ILA_Characterization/ip/ILA_Characterization_clk_wiz_0_0/ILA_Characterization_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Characterization_clk_wiz_0_0 || ORIG_REF_NAME==ILA_Characterization_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ILA_Characterization/ip/ILA_Characterization_c_counter_binary_0_0/ILA_Characterization_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Characterization_c_counter_binary_0_0 || ORIG_REF_NAME==ILA_Characterization_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/ILA_Characterization/ip/ILA_Characterization_util_vector_logic_0_0/ILA_Characterization_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Characterization_util_vector_logic_0_0 || ORIG_REF_NAME==ILA_Characterization_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/ILA_Characterization/ip/ILA_Characterization_ila_0_0/ILA_Characterization_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Characterization_ila_0_0 || ORIG_REF_NAME==ILA_Characterization_ila_0_0} -quiet] -quiet

# XDC: bd/ILA_Characterization/ILA_Characterization_ooc.xdc
