# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/depot/Projects/ETF_2021/EmbeddedTestFramework/EmbeddedTestFramework.srcs/sources_1/bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_clk_wiz_0_0/EmbeddedTestFramework_clk_wiz_0_0.xci
# IP: The module: 'EmbeddedTestFramework_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/depot/Projects/ETF_2021/EmbeddedTestFramework/EmbeddedTestFramework.srcs/sources_1/bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_clk_wiz_0_0/EmbeddedTestFramework_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'EmbeddedTestFramework_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/depot/Projects/ETF_2021/EmbeddedTestFramework/EmbeddedTestFramework.srcs/sources_1/bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_clk_wiz_0_0/EmbeddedTestFramework_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'EmbeddedTestFramework_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/depot/Projects/ETF_2021/EmbeddedTestFramework/EmbeddedTestFramework.srcs/sources_1/bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_clk_wiz_0_0/EmbeddedTestFramework_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'EmbeddedTestFramework_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/depot/Projects/ETF_2021/EmbeddedTestFramework/EmbeddedTestFramework.srcs/sources_1/bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_clk_wiz_0_0/EmbeddedTestFramework_clk_wiz_0_0.xci
# IP: The module: 'EmbeddedTestFramework_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/depot/Projects/ETF_2021/EmbeddedTestFramework/EmbeddedTestFramework.srcs/sources_1/bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_clk_wiz_0_0/EmbeddedTestFramework_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'EmbeddedTestFramework_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/depot/Projects/ETF_2021/EmbeddedTestFramework/EmbeddedTestFramework.srcs/sources_1/bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_clk_wiz_0_0/EmbeddedTestFramework_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'EmbeddedTestFramework_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/depot/Projects/ETF_2021/EmbeddedTestFramework/EmbeddedTestFramework.srcs/sources_1/bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_clk_wiz_0_0/EmbeddedTestFramework_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'EmbeddedTestFramework_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
