# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/depot/Projects/ETF_2021/ILA_Interrupt/ILA_Interrupt.srcs/sources_1/bd/ILA_Interrupt/ip/ILA_Interrupt_processing_system7_0_0/ILA_Interrupt_processing_system7_0_0.xci
# IP: The module: 'ILA_Interrupt_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/depot/Projects/ETF_2021/ILA_Interrupt/ILA_Interrupt.srcs/sources_1/bd/ILA_Interrupt/ip/ILA_Interrupt_processing_system7_0_0/ILA_Interrupt_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_Interrupt_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/depot/Projects/ETF_2021/ILA_Interrupt/ILA_Interrupt.srcs/sources_1/bd/ILA_Interrupt/ip/ILA_Interrupt_processing_system7_0_0/ILA_Interrupt_processing_system7_0_0.xci
# IP: The module: 'ILA_Interrupt_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/depot/Projects/ETF_2021/ILA_Interrupt/ILA_Interrupt.srcs/sources_1/bd/ILA_Interrupt/ip/ILA_Interrupt_processing_system7_0_0/ILA_Interrupt_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_Interrupt_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
