# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ILA_Trigger/ILA_Trigger.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Trigger || ORIG_REF_NAME==ILA_Trigger} -quiet] -quiet

# IP: bd/ILA_Trigger/ip/ILA_Trigger_processing_system7_0_0/ILA_Trigger_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Trigger_processing_system7_0_0 || ORIG_REF_NAME==ILA_Trigger_processing_system7_0_0} -quiet] -quiet

# IP: bd/ILA_Trigger/ip/ILA_Trigger_AXITrigger_0_0/ILA_Trigger_AXITrigger_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Trigger_AXITrigger_0_0 || ORIG_REF_NAME==ILA_Trigger_AXITrigger_0_0} -quiet] -quiet

# IP: bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/ILA_Trigger_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Trigger_axi_smc_0 || ORIG_REF_NAME==ILA_Trigger_axi_smc_0} -quiet] -quiet

# IP: bd/ILA_Trigger/ip/ILA_Trigger_rst_ps7_0_100M_0/ILA_Trigger_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Trigger_rst_ps7_0_100M_0 || ORIG_REF_NAME==ILA_Trigger_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/ILA_Trigger/ip/ILA_Trigger_axi_gpio_0_0/ILA_Trigger_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Trigger_axi_gpio_0_0 || ORIG_REF_NAME==ILA_Trigger_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/ILA_Trigger_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Trigger_system_ila_0_0 || ORIG_REF_NAME==ILA_Trigger_system_ila_0_0} -quiet] -quiet

# IP: bd/ILA_Trigger/ip/ILA_Trigger_xlconstant_0_0/ILA_Trigger_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Trigger_xlconstant_0_0 || ORIG_REF_NAME==ILA_Trigger_xlconstant_0_0} -quiet] -quiet

# XDC: bd/ILA_Trigger/ILA_Trigger_ooc.xdc
