# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/Sampler_Characterization/Sampler_Characterization.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sampler_Characterization || ORIG_REF_NAME==Sampler_Characterization} -quiet] -quiet

# IP: bd/Sampler_Characterization/ip/Sampler_Characterization_processing_system7_0_0/Sampler_Characterization_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sampler_Characterization_processing_system7_0_0 || ORIG_REF_NAME==Sampler_Characterization_processing_system7_0_0} -quiet] -quiet

# IP: bd/Sampler_Characterization/ip/Sampler_Characterization_clk_wiz_0_0/Sampler_Characterization_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sampler_Characterization_clk_wiz_0_0 || ORIG_REF_NAME==Sampler_Characterization_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Sampler_Characterization/ip/Sampler_Characterization_c_counter_binary_0_0/Sampler_Characterization_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sampler_Characterization_c_counter_binary_0_0 || ORIG_REF_NAME==Sampler_Characterization_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/Sampler_Characterization/ip/Sampler_Characterization_util_vector_logic_0_0/Sampler_Characterization_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sampler_Characterization_util_vector_logic_0_0 || ORIG_REF_NAME==Sampler_Characterization_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/Sampler_Characterization/ip/Sampler_Characterization_AXI_Sampler_0_0/Sampler_Characterization_AXI_Sampler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sampler_Characterization_AXI_Sampler_0_0 || ORIG_REF_NAME==Sampler_Characterization_AXI_Sampler_0_0} -quiet] -quiet

# IP: bd/Sampler_Characterization/ip/Sampler_Characterization_axi_intc_0_1/Sampler_Characterization_axi_intc_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sampler_Characterization_axi_intc_0_1 || ORIG_REF_NAME==Sampler_Characterization_axi_intc_0_1} -quiet] -quiet

# IP: bd/Sampler_Characterization/ip/Sampler_Characterization_axi_interconnect_0_0/Sampler_Characterization_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sampler_Characterization_axi_interconnect_0_0 || ORIG_REF_NAME==Sampler_Characterization_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/Sampler_Characterization/ip/Sampler_Characterization_rst_ps7_0_100M_0/Sampler_Characterization_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sampler_Characterization_rst_ps7_0_100M_0 || ORIG_REF_NAME==Sampler_Characterization_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Sampler_Characterization/ip/Sampler_Characterization_xbar_0/Sampler_Characterization_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sampler_Characterization_xbar_0 || ORIG_REF_NAME==Sampler_Characterization_xbar_0} -quiet] -quiet

# IP: bd/Sampler_Characterization/ip/Sampler_Characterization_AXITrigger_0_0/Sampler_Characterization_AXITrigger_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sampler_Characterization_AXITrigger_0_0 || ORIG_REF_NAME==Sampler_Characterization_AXITrigger_0_0} -quiet] -quiet

# IP: bd/Sampler_Characterization/ip/Sampler_Characterization_auto_pc_0/Sampler_Characterization_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sampler_Characterization_auto_pc_0 || ORIG_REF_NAME==Sampler_Characterization_auto_pc_0} -quiet] -quiet

# IP: bd/Sampler_Characterization/ip/Sampler_Characterization_auto_pc_1/Sampler_Characterization_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sampler_Characterization_auto_pc_1 || ORIG_REF_NAME==Sampler_Characterization_auto_pc_1} -quiet] -quiet

# XDC: bd/Sampler_Characterization/Sampler_Characterization_ooc.xdc
