set_property PACKAGE_PIN L16 [get_ports sys_clock]
set_property PACKAGE_PIN Y16 [get_ports reset_rtl]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clock]
set_property IOSTANDARD LVCMOS33 [get_ports reset_rtl]


# -- Switches --
set_property PACKAGE_PIN G15 [get_ports GPIO_1_tri_i[0]]
set_property PACKAGE_PIN P15 [get_ports GPIO_1_tri_i[1]]
set_property PACKAGE_PIN W13 [get_ports GPIO_1_tri_i[2]]
set_property PACKAGE_PIN T16 [get_ports GPIO_1_tri_i[3]]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_1_tri_i[0]]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_1_tri_i[1]]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_1_tri_i[2]]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_1_tri_i[3]]

# -- LEDs --
set_property PACKAGE_PIN M14 [get_ports GPIO_0_tri_o[0]]
set_property PACKAGE_PIN M15 [get_ports GPIO_0_tri_o[1]]
set_property PACKAGE_PIN G14 [get_ports GPIO_0_tri_o[2]]
set_property PACKAGE_PIN D18 [get_ports GPIO_0_tri_o[3]]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_0_tri_o[0]]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_0_tri_o[1]]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_0_tri_o[2]]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_0_tri_o[3]]

# -- VGA --
set_property IOSTANDARD LVCMOS33 [get_ports {VGA[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]

set_property PACKAGE_PIN P20 [get_ports {VGA[0]}]
set_property PACKAGE_PIN M20 [get_ports {VGA[1]}]
set_property PACKAGE_PIN K19 [get_ports {VGA[2]}]
set_property PACKAGE_PIN J18 [get_ports {VGA[3]}]
set_property PACKAGE_PIN G19 [get_ports {VGA[4]}]
set_property PACKAGE_PIN H18 [get_ports {VGA[5]}]
set_property PACKAGE_PIN N20 [get_ports {VGA[6]}]
set_property PACKAGE_PIN L19 [get_ports {VGA[7]}]
set_property PACKAGE_PIN J19 [get_ports {VGA[8]}]
set_property PACKAGE_PIN H20 [get_ports {VGA[9]}]
set_property PACKAGE_PIN F20 [get_ports {VGA[10]}]
set_property PACKAGE_PIN M19 [get_ports {VGA[11]}]
set_property PACKAGE_PIN L20 [get_ports {VGA[12]}]
set_property PACKAGE_PIN J20 [get_ports {VGA[13]}]
set_property PACKAGE_PIN G20 [get_ports {VGA[14]}]
set_property PACKAGE_PIN F19 [get_ports {VGA[15]}]

set_property PACKAGE_PIN R19 [get_ports vsync]
set_property PACKAGE_PIN P19 [get_ports hsync]
