# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/SystemILATest/SystemILATest.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SystemILATest || ORIG_REF_NAME==SystemILATest} -quiet] -quiet

# IP: bd/SystemILATest/ip/SystemILATest_processing_system7_0_0/SystemILATest_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SystemILATest_processing_system7_0_0 || ORIG_REF_NAME==SystemILATest_processing_system7_0_0} -quiet] -quiet

# IP: bd/SystemILATest/ip/SystemILATest_ps7_0_axi_periph_0/SystemILATest_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SystemILATest_ps7_0_axi_periph_0 || ORIG_REF_NAME==SystemILATest_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/SystemILATest/ip/SystemILATest_rst_ps7_0_100M_0/SystemILATest_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SystemILATest_rst_ps7_0_100M_0 || ORIG_REF_NAME==SystemILATest_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/SystemILATest/ip/SystemILATest_AXI_Injector_0_0/SystemILATest_AXI_Injector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SystemILATest_AXI_Injector_0_0 || ORIG_REF_NAME==SystemILATest_AXI_Injector_0_0} -quiet] -quiet

# IP: bd/SystemILATest/ip/SystemILATest_clk_wiz_0_0/SystemILATest_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SystemILATest_clk_wiz_0_0 || ORIG_REF_NAME==SystemILATest_clk_wiz_0_0} -quiet] -quiet

# IP: bd/SystemILATest/ip/SystemILATest_util_reduced_logic_0_0/SystemILATest_util_reduced_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SystemILATest_util_reduced_logic_0_0 || ORIG_REF_NAME==SystemILATest_util_reduced_logic_0_0} -quiet] -quiet

# IP: bd/SystemILATest/ip/SystemILATest_util_reduced_logic_1_0/SystemILATest_util_reduced_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SystemILATest_util_reduced_logic_1_0 || ORIG_REF_NAME==SystemILATest_util_reduced_logic_1_0} -quiet] -quiet

# IP: bd/SystemILATest/ip/SystemILATest_system_ila_0_0/SystemILATest_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SystemILATest_system_ila_0_0 || ORIG_REF_NAME==SystemILATest_system_ila_0_0} -quiet] -quiet

# IP: bd/SystemILATest/ip/SystemILATest_auto_pc_0/SystemILATest_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SystemILATest_auto_pc_0 || ORIG_REF_NAME==SystemILATest_auto_pc_0} -quiet] -quiet

# XDC: bd/SystemILATest/SystemILATest_ooc.xdc
