webtalk_init -webtalk_dir d:/depot/projects/etf/embeddedtestframework/embeddedtestframework.tmp/interruptgenerator_v1_0_project_deteme11-11-2022/InterruptGenerator_v1_0_project_deteMe11-11-2022.sim/sim_1/behav/xsim/xsim.dir/InterruptMultiReg_v1_0_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Nov 11 07:28:23 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211942497_0_0_760" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b39762dd-8c10-4dc1-a744-2c1095bf2c79" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "771ff3e4471847fcb7b49575b0f85fd3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "21 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6304_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4105301065 -regid "211942497_0_0_760" -xml d:/depot/projects/etf/embeddedtestframework/embeddedtestframework.tmp/interruptgenerator_v1_0_project_deteme11-11-2022/InterruptGenerator_v1_0_project_deteMe11-11-2022.sim/sim_1/behav/xsim/xsim.dir/InterruptMultiReg_v1_0_behav/webtalk/usage_statistics_ext_xsim.xml -html d:/depot/projects/etf/embeddedtestframework/embeddedtestframework.tmp/interruptgenerator_v1_0_project_deteme11-11-2022/InterruptGenerator_v1_0_project_deteMe11-11-2022.sim/sim_1/behav/xsim/xsim.dir/InterruptMultiReg_v1_0_behav/webtalk/usage_statistics_ext_xsim.html -wdm d:/depot/projects/etf/embeddedtestframework/embeddedtestframework.tmp/interruptgenerator_v1_0_project_deteme11-11-2022/InterruptGenerator_v1_0_project_deteMe11-11-2022.sim/sim_1/behav/xsim/xsim.dir/InterruptMultiReg_v1_0_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
