# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ILA_ClockDivider/ILA_ClockDivider.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_ClockDivider || ORIG_REF_NAME==ILA_ClockDivider} -quiet] -quiet

# IP: bd/ILA_ClockDivider/ip/ILA_ClockDivider_processing_system7_0_0/ILA_ClockDivider_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_ClockDivider_processing_system7_0_0 || ORIG_REF_NAME==ILA_ClockDivider_processing_system7_0_0} -quiet] -quiet

# IP: bd/ILA_ClockDivider/ip/ILA_ClockDivider_ClockDivider_0_0/ILA_ClockDivider_ClockDivider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_ClockDivider_ClockDivider_0_0 || ORIG_REF_NAME==ILA_ClockDivider_ClockDivider_0_0} -quiet] -quiet

# IP: bd/ILA_ClockDivider/ip/ILA_ClockDivider_axi_smc_0/ILA_ClockDivider_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_ClockDivider_axi_smc_0 || ORIG_REF_NAME==ILA_ClockDivider_axi_smc_0} -quiet] -quiet

# IP: bd/ILA_ClockDivider/ip/ILA_ClockDivider_rst_ps7_0_100M_0/ILA_ClockDivider_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_ClockDivider_rst_ps7_0_100M_0 || ORIG_REF_NAME==ILA_ClockDivider_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/ILA_ClockDivider/ip/ILA_ClockDivider_system_ila_0_0/ILA_ClockDivider_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_ClockDivider_system_ila_0_0 || ORIG_REF_NAME==ILA_ClockDivider_system_ila_0_0} -quiet] -quiet

# XDC: bd/ILA_ClockDivider/ILA_ClockDivider_ooc.xdc
