set_property SRC_FILE_INFO {cfile:D:/depot/Projects/ETF_2021/Sampler_Characterization/Sampler_Characterization.srcs/constrs_1/new/constraints.xdc rfile:../../../Sampler_Characterization.srcs/constrs_1/new/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L16 [get_ports sys_clock]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T16 [get_ports reset_rtl]
