# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/TestMultiReg/TestMultiReg.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TestMultiReg || ORIG_REF_NAME==TestMultiReg} -quiet] -quiet

# IP: bd/TestMultiReg/ip/TestMultiReg_processing_system7_0_0/TestMultiReg_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TestMultiReg_processing_system7_0_0 || ORIG_REF_NAME==TestMultiReg_processing_system7_0_0} -quiet] -quiet

# IP: bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/TestMultiReg_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TestMultiReg_axi_smc_0 || ORIG_REF_NAME==TestMultiReg_axi_smc_0} -quiet] -quiet

# IP: bd/TestMultiReg/ip/TestMultiReg_rst_ps7_0_100M_0/TestMultiReg_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TestMultiReg_rst_ps7_0_100M_0 || ORIG_REF_NAME==TestMultiReg_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/TestMultiReg/ip/TestMultiReg_MUX_0_0/TestMultiReg_MUX_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TestMultiReg_MUX_0_0 || ORIG_REF_NAME==TestMultiReg_MUX_0_0} -quiet] -quiet

# IP: bd/TestMultiReg/ip/TestMultiReg_xlconcat_0_0/TestMultiReg_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TestMultiReg_xlconcat_0_0 || ORIG_REF_NAME==TestMultiReg_xlconcat_0_0} -quiet] -quiet

# IP: bd/TestMultiReg/ip/TestMultiReg_ClockDivider_0_0/TestMultiReg_ClockDivider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TestMultiReg_ClockDivider_0_0 || ORIG_REF_NAME==TestMultiReg_ClockDivider_0_0} -quiet] -quiet

# IP: bd/TestMultiReg/ip/TestMultiReg_AXI_Injector_0_0/TestMultiReg_AXI_Injector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TestMultiReg_AXI_Injector_0_0 || ORIG_REF_NAME==TestMultiReg_AXI_Injector_0_0} -quiet] -quiet

# IP: bd/TestMultiReg/ip/TestMultiReg_AXI_Sampler_0_0/TestMultiReg_AXI_Sampler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TestMultiReg_AXI_Sampler_0_0 || ORIG_REF_NAME==TestMultiReg_AXI_Sampler_0_0} -quiet] -quiet

# IP: bd/TestMultiReg/ip/TestMultiReg_InterruptGenerator_0_0/TestMultiReg_InterruptGenerator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TestMultiReg_InterruptGenerator_0_0 || ORIG_REF_NAME==TestMultiReg_InterruptGenerator_0_0} -quiet] -quiet

# IP: bd/TestMultiReg/ip/TestMultiReg_InterruptGenerator_1_0/TestMultiReg_InterruptGenerator_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TestMultiReg_InterruptGenerator_1_0 || ORIG_REF_NAME==TestMultiReg_InterruptGenerator_1_0} -quiet] -quiet

# XDC: bd/TestMultiReg/TestMultiReg_ooc.xdc
