# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.cache/wt [current_project]
set_property parent.project_path C:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.xpr [current_project]
set_property XPM_LIBRARIES {XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths {
  c:/Users/Robert/xilinx_projects/ip_repo/ClockDivider_1.0
  c:/Users/Robert/xilinx_projects/ip_repo/TestSampler_1.0
  c:/Users/Robert/xilinx_projects/ip_repo/TestSampler_1.0
  c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/new
  c:/Users/Robert/xilinx_projects/ip_repo/InterruptMultiReg_1.0
  c:/Users/Robert/xilinx_projects/ip_repo/TestMultiReg_1.0
  c:/Users/Robert/xilinx_projects/clock_enabler/clock_enabler.srcs/sources_1/imports/sources
} [current_project]
set_property ip_output_repo c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/hdl/TestMultiReg_wrapper.vhd
add_files C:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/TestMultiReg.bd
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_processing_system7_0_0/TestMultiReg_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_10/bd_e613_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_16/bd_e613_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_23/bd_e613_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_30/bd_e613_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_37/bd_e613_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_44/bd_e613_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_45/bd_e613_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_46/bd_e613_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_47/bd_e613_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_48/bd_e613_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_49/bd_e613_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_38/bd_e613_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_39/bd_e613_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_40/bd_e613_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_41/bd_e613_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_42/bd_e613_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_31/bd_e613_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_32/bd_e613_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_33/bd_e613_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_34/bd_e613_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_35/bd_e613_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_24/bd_e613_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_25/bd_e613_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_26/bd_e613_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_27/bd_e613_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_28/bd_e613_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_17/bd_e613_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_18/bd_e613_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_19/bd_e613_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_20/bd_e613_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_21/bd_e613_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_11/bd_e613_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_12/bd_e613_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_13/bd_e613_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_14/bd_e613_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_15/bd_e613_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_2/bd_e613_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_3/bd_e613_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_4/bd_e613_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_5/bd_e613_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_6/bd_e613_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_1/bd_e613_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/bd_0/ip/ip_1/bd_e613_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_rst_ps7_0_100M_0/TestMultiReg_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_rst_ps7_0_100M_0/TestMultiReg_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/ip/TestMultiReg_rst_ps7_0_100M_0/TestMultiReg_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/sources_1/bd/TestMultiReg/TestMultiReg_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/Robert/xilinx_projects/TestMultiReg/TestMultiReg.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top TestMultiReg_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TestMultiReg_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TestMultiReg_wrapper_utilization_synth.rpt -pb TestMultiReg_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
