# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/SystemILBTest/SystemILBTest.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SystemILBTest || ORIG_REF_NAME==SystemILBTest} -quiet] -quiet

# IP: bd/SystemILBTest/ip/SystemILBTest_processing_system7_0_0/SystemILBTest_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SystemILBTest_processing_system7_0_0 || ORIG_REF_NAME==SystemILBTest_processing_system7_0_0} -quiet] -quiet

# IP: bd/SystemILBTest/ip/SystemILBTest_AXI_Sampler_0_0/SystemILBTest_AXI_Sampler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SystemILBTest_AXI_Sampler_0_0 || ORIG_REF_NAME==SystemILBTest_AXI_Sampler_0_0} -quiet] -quiet

# IP: bd/SystemILBTest/ip/SystemILBTest_rst_ps7_0_100M_0/SystemILBTest_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SystemILBTest_rst_ps7_0_100M_0 || ORIG_REF_NAME==SystemILBTest_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/SystemILBTest/ip/SystemILBTest_c_counter_binary_0_0/SystemILBTest_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SystemILBTest_c_counter_binary_0_0 || ORIG_REF_NAME==SystemILBTest_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/SystemILBTest/ip/SystemILBTest_clk_wiz_0_0/SystemILBTest_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SystemILBTest_clk_wiz_0_0 || ORIG_REF_NAME==SystemILBTest_clk_wiz_0_0} -quiet] -quiet

# IP: bd/SystemILBTest/ip/SystemILBTest_util_vector_logic_0_0/SystemILBTest_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SystemILBTest_util_vector_logic_0_0 || ORIG_REF_NAME==SystemILBTest_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/SystemILBTest/ip/SystemILBTest_system_ila_0_0/SystemILBTest_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SystemILBTest_system_ila_0_0 || ORIG_REF_NAME==SystemILBTest_system_ila_0_0} -quiet] -quiet

# IP: bd/SystemILBTest/ip/SystemILBTest_axi_mem_intercon_0/SystemILBTest_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SystemILBTest_axi_mem_intercon_0 || ORIG_REF_NAME==SystemILBTest_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/SystemILBTest/ip/SystemILBTest_auto_pc_0/SystemILBTest_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SystemILBTest_auto_pc_0 || ORIG_REF_NAME==SystemILBTest_auto_pc_0} -quiet] -quiet

# XDC: bd/SystemILBTest/SystemILBTest_ooc.xdc
