# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/ILA_Trigger_system_ila_0_0.xci
# IP: The module: 'ILA_Trigger_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/bd_deaa.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_deaa || ORIG_REF_NAME==bd_deaa} -quiet] -quiet

# IP: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_0/bd_deaa_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_deaa_ila_lib_0 || ORIG_REF_NAME==bd_deaa_ila_lib_0} -quiet] -quiet

# IP: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_1/bd_deaa_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_deaa_g_inst_0 || ORIG_REF_NAME==bd_deaa_g_inst_0} -quiet] -quiet

# IP: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_2/bd_deaa_slot_0_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_deaa_slot_0_aw_0 || ORIG_REF_NAME==bd_deaa_slot_0_aw_0} -quiet] -quiet

# IP: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_3/bd_deaa_slot_0_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_deaa_slot_0_w_0 || ORIG_REF_NAME==bd_deaa_slot_0_w_0} -quiet] -quiet

# IP: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_4/bd_deaa_slot_0_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_deaa_slot_0_b_0 || ORIG_REF_NAME==bd_deaa_slot_0_b_0} -quiet] -quiet

# IP: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_5/bd_deaa_slot_0_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_deaa_slot_0_ar_0 || ORIG_REF_NAME==bd_deaa_slot_0_ar_0} -quiet] -quiet

# IP: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_6/bd_deaa_slot_0_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_deaa_slot_0_r_0 || ORIG_REF_NAME==bd_deaa_slot_0_r_0} -quiet] -quiet

# XDC: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/ILA_Trigger_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_Trigger_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_deaa_ila_lib_0 || ORIG_REF_NAME==bd_deaa_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_deaa_ila_lib_0 || ORIG_REF_NAME==bd_deaa_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_0/bd_deaa_ila_lib_0_ooc.xdc

# XDC: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/bd_deaa_ooc.xdc

# IP: C:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/ILA_Trigger_system_ila_0_0.xci
# IP: The module: 'ILA_Trigger_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/bd_deaa.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_deaa || ORIG_REF_NAME==bd_deaa} -quiet] -quiet

# IP: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_0/bd_deaa_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_deaa_ila_lib_0 || ORIG_REF_NAME==bd_deaa_ila_lib_0} -quiet] -quiet

# IP: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_1/bd_deaa_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_deaa_g_inst_0 || ORIG_REF_NAME==bd_deaa_g_inst_0} -quiet] -quiet

# IP: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_2/bd_deaa_slot_0_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_deaa_slot_0_aw_0 || ORIG_REF_NAME==bd_deaa_slot_0_aw_0} -quiet] -quiet

# IP: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_3/bd_deaa_slot_0_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_deaa_slot_0_w_0 || ORIG_REF_NAME==bd_deaa_slot_0_w_0} -quiet] -quiet

# IP: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_4/bd_deaa_slot_0_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_deaa_slot_0_b_0 || ORIG_REF_NAME==bd_deaa_slot_0_b_0} -quiet] -quiet

# IP: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_5/bd_deaa_slot_0_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_deaa_slot_0_ar_0 || ORIG_REF_NAME==bd_deaa_slot_0_ar_0} -quiet] -quiet

# IP: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_6/bd_deaa_slot_0_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_deaa_slot_0_r_0 || ORIG_REF_NAME==bd_deaa_slot_0_r_0} -quiet] -quiet

# XDC: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/ILA_Trigger_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_Trigger_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_deaa_ila_lib_0 || ORIG_REF_NAME==bd_deaa_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_deaa_ila_lib_0 || ORIG_REF_NAME==bd_deaa_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_0/bd_deaa_ila_lib_0_ooc.xdc

# XDC: c:/Users/Robert/xilinx_projects/ILA_Trigger/ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/bd_deaa_ooc.xdc
