# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ILA_Interrupt/ILA_Interrupt.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Interrupt || ORIG_REF_NAME==ILA_Interrupt} -quiet] -quiet

# IP: bd/ILA_Interrupt/ip/ILA_Interrupt_processing_system7_0_0/ILA_Interrupt_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Interrupt_processing_system7_0_0 || ORIG_REF_NAME==ILA_Interrupt_processing_system7_0_0} -quiet] -quiet

# IP: bd/ILA_Interrupt/ip/ILA_Interrupt_InterruptGenerator_0_1/ILA_Interrupt_InterruptGenerator_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Interrupt_InterruptGenerator_0_1 || ORIG_REF_NAME==ILA_Interrupt_InterruptGenerator_0_1} -quiet] -quiet

# IP: bd/ILA_Interrupt/ip/ILA_Interrupt_ps7_0_axi_periph_0/ILA_Interrupt_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Interrupt_ps7_0_axi_periph_0 || ORIG_REF_NAME==ILA_Interrupt_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ILA_Interrupt/ip/ILA_Interrupt_rst_ps7_0_100M_0/ILA_Interrupt_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Interrupt_rst_ps7_0_100M_0 || ORIG_REF_NAME==ILA_Interrupt_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/ILA_Interrupt/ip/ILA_Interrupt_axi_gpio_0_0/ILA_Interrupt_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Interrupt_axi_gpio_0_0 || ORIG_REF_NAME==ILA_Interrupt_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ILA_Interrupt/ip/ILA_Interrupt_system_ila_0_0/ILA_Interrupt_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Interrupt_system_ila_0_0 || ORIG_REF_NAME==ILA_Interrupt_system_ila_0_0} -quiet] -quiet

# IP: bd/ILA_Interrupt/ip/ILA_Interrupt_xbar_0/ILA_Interrupt_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Interrupt_xbar_0 || ORIG_REF_NAME==ILA_Interrupt_xbar_0} -quiet] -quiet

# IP: bd/ILA_Interrupt/ip/ILA_Interrupt_auto_pc_0/ILA_Interrupt_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Interrupt_auto_pc_0 || ORIG_REF_NAME==ILA_Interrupt_auto_pc_0} -quiet] -quiet

# XDC: bd/ILA_Interrupt/ILA_Interrupt_ooc.xdc
