# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/EmbeddedTestFramework/EmbeddedTestFramework.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework || ORIG_REF_NAME==EmbeddedTestFramework} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_processing_system7_0_0/EmbeddedTestFramework_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_processing_system7_0_0 || ORIG_REF_NAME==EmbeddedTestFramework_processing_system7_0_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_xlconcat_0_0/EmbeddedTestFramework_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_xlconcat_0_0 || ORIG_REF_NAME==EmbeddedTestFramework_xlconcat_0_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_AXI_Sampler_0_0/EmbeddedTestFramework_AXI_Sampler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_AXI_Sampler_0_0 || ORIG_REF_NAME==EmbeddedTestFramework_AXI_Sampler_0_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_InterruptGenerator_0_0/EmbeddedTestFramework_InterruptGenerator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_InterruptGenerator_0_0 || ORIG_REF_NAME==EmbeddedTestFramework_InterruptGenerator_0_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_AXITrigger_0_0/EmbeddedTestFramework_AXITrigger_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_AXITrigger_0_0 || ORIG_REF_NAME==EmbeddedTestFramework_AXITrigger_0_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_InterruptGenerator_1_0/EmbeddedTestFramework_InterruptGenerator_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_InterruptGenerator_1_0 || ORIG_REF_NAME==EmbeddedTestFramework_InterruptGenerator_1_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_AXI_Injector_0_0/EmbeddedTestFramework_AXI_Injector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_AXI_Injector_0_0 || ORIG_REF_NAME==EmbeddedTestFramework_AXI_Injector_0_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_ps7_0_axi_periph_0/EmbeddedTestFramework_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_ps7_0_axi_periph_0 || ORIG_REF_NAME==EmbeddedTestFramework_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_rst_ps7_0_100M_0/EmbeddedTestFramework_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_rst_ps7_0_100M_0 || ORIG_REF_NAME==EmbeddedTestFramework_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_xbar_0/EmbeddedTestFramework_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_xbar_0 || ORIG_REF_NAME==EmbeddedTestFramework_xbar_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_ClockDivider_0_0/EmbeddedTestFramework_ClockDivider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_ClockDivider_0_0 || ORIG_REF_NAME==EmbeddedTestFramework_ClockDivider_0_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_tie_low_0_0/EmbeddedTestFramework_tie_low_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_tie_low_0_0 || ORIG_REF_NAME==EmbeddedTestFramework_tie_low_0_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_DUT_0_0/EmbeddedTestFramework_DUT_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_DUT_0_0 || ORIG_REF_NAME==EmbeddedTestFramework_DUT_0_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_v_tc_0_0/EmbeddedTestFramework_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_v_tc_0_0 || ORIG_REF_NAME==EmbeddedTestFramework_v_tc_0_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_clk_wiz_0_0/EmbeddedTestFramework_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_clk_wiz_0_0 || ORIG_REF_NAME==EmbeddedTestFramework_clk_wiz_0_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_Blanker_0_0/EmbeddedTestFramework_Blanker_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_Blanker_0_0 || ORIG_REF_NAME==EmbeddedTestFramework_Blanker_0_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_Reducer32to16_0_0/EmbeddedTestFramework_Reducer32to16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_Reducer32to16_0_0 || ORIG_REF_NAME==EmbeddedTestFramework_Reducer32to16_0_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_axi_gpio_0_0/EmbeddedTestFramework_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_axi_gpio_0_0 || ORIG_REF_NAME==EmbeddedTestFramework_axi_gpio_0_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_blk_mem_gen_0_0/EmbeddedTestFramework_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_blk_mem_gen_0_0 || ORIG_REF_NAME==EmbeddedTestFramework_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_axi_bram_ctrl_0_0/EmbeddedTestFramework_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_axi_bram_ctrl_0_0 || ORIG_REF_NAME==EmbeddedTestFramework_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_InterruptGenerator_0_1/EmbeddedTestFramework_InterruptGenerator_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_InterruptGenerator_0_1 || ORIG_REF_NAME==EmbeddedTestFramework_InterruptGenerator_0_1} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_FallingEdgeDetect_0_0/EmbeddedTestFramework_FallingEdgeDetect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_FallingEdgeDetect_0_0 || ORIG_REF_NAME==EmbeddedTestFramework_FallingEdgeDetect_0_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_FallingEdgeDetect_1_0/EmbeddedTestFramework_FallingEdgeDetect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_FallingEdgeDetect_1_0 || ORIG_REF_NAME==EmbeddedTestFramework_FallingEdgeDetect_1_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_InterruptGenerator_0_2/EmbeddedTestFramework_InterruptGenerator_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_InterruptGenerator_0_2 || ORIG_REF_NAME==EmbeddedTestFramework_InterruptGenerator_0_2} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_c_counter_binary_0_0/EmbeddedTestFramework_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_c_counter_binary_0_0 || ORIG_REF_NAME==EmbeddedTestFramework_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_GatedClockEnable_0_0/EmbeddedTestFramework_GatedClockEnable_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_GatedClockEnable_0_0 || ORIG_REF_NAME==EmbeddedTestFramework_GatedClockEnable_0_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_axi_gpio_1_0/EmbeddedTestFramework_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_axi_gpio_1_0 || ORIG_REF_NAME==EmbeddedTestFramework_axi_gpio_1_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_util_vector_logic_0_0/EmbeddedTestFramework_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_util_vector_logic_0_0 || ORIG_REF_NAME==EmbeddedTestFramework_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_auto_pc_5/EmbeddedTestFramework_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_auto_pc_5 || ORIG_REF_NAME==EmbeddedTestFramework_auto_pc_5} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_auto_pc_4/EmbeddedTestFramework_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_auto_pc_4 || ORIG_REF_NAME==EmbeddedTestFramework_auto_pc_4} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_auto_pc_3/EmbeddedTestFramework_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_auto_pc_3 || ORIG_REF_NAME==EmbeddedTestFramework_auto_pc_3} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_auto_pc_2/EmbeddedTestFramework_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_auto_pc_2 || ORIG_REF_NAME==EmbeddedTestFramework_auto_pc_2} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_auto_pc_1/EmbeddedTestFramework_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_auto_pc_1 || ORIG_REF_NAME==EmbeddedTestFramework_auto_pc_1} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_auto_pc_0/EmbeddedTestFramework_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_auto_pc_0 || ORIG_REF_NAME==EmbeddedTestFramework_auto_pc_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_s00_data_fifo_0/EmbeddedTestFramework_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_s00_data_fifo_0 || ORIG_REF_NAME==EmbeddedTestFramework_s00_data_fifo_0} -quiet] -quiet

# IP: bd/EmbeddedTestFramework/ip/EmbeddedTestFramework_auto_pc_6/EmbeddedTestFramework_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EmbeddedTestFramework_auto_pc_6 || ORIG_REF_NAME==EmbeddedTestFramework_auto_pc_6} -quiet] -quiet

# XDC: bd/EmbeddedTestFramework/EmbeddedTestFramework_ooc.xdc
