# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/VIO_Latency/VIO_Latency.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VIO_Latency || ORIG_REF_NAME==VIO_Latency} -quiet] -quiet

# IP: bd/VIO_Latency/ip/VIO_Latency_clk_wiz_0_0/VIO_Latency_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VIO_Latency_clk_wiz_0_0 || ORIG_REF_NAME==VIO_Latency_clk_wiz_0_0} -quiet] -quiet

# IP: bd/VIO_Latency/ip/VIO_Latency_ila_0_0/VIO_Latency_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VIO_Latency_ila_0_0 || ORIG_REF_NAME==VIO_Latency_ila_0_0} -quiet] -quiet

# IP: bd/VIO_Latency/ip/VIO_Latency_vio_0_0/VIO_Latency_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VIO_Latency_vio_0_0 || ORIG_REF_NAME==VIO_Latency_vio_0_0} -quiet] -quiet

# IP: bd/VIO_Latency/ip/VIO_Latency_c_counter_binary_0_0/VIO_Latency_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VIO_Latency_c_counter_binary_0_0 || ORIG_REF_NAME==VIO_Latency_c_counter_binary_0_0} -quiet] -quiet

# XDC: bd/VIO_Latency/VIO_Latency_ooc.xdc
