vlib work
vlib activehdl

vlib activehdl/xilinx_vip
vlib activehdl/xil_defaultlib
vlib activehdl/xpm
vlib activehdl/axi_infrastructure_v1_1_0
vlib activehdl/smartconnect_v1_0
vlib activehdl/axi_protocol_checker_v2_0_3
vlib activehdl/axi_vip_v1_1_3
vlib activehdl/processing_system7_vip_v1_0_5
vlib activehdl/xlconstant_v1_1_5
vlib activehdl/lib_cdc_v1_0_2
vlib activehdl/proc_sys_reset_v5_0_12
vlib activehdl/axi_lite_ipif_v3_0_4
vlib activehdl/interrupt_control_v3_1_4
vlib activehdl/axi_gpio_v2_0_19
vlib activehdl/gigantic_mux
vlib activehdl/xlconcat_v2_1_1

vmap xilinx_vip activehdl/xilinx_vip
vmap xil_defaultlib activehdl/xil_defaultlib
vmap xpm activehdl/xpm
vmap axi_infrastructure_v1_1_0 activehdl/axi_infrastructure_v1_1_0
vmap smartconnect_v1_0 activehdl/smartconnect_v1_0
vmap axi_protocol_checker_v2_0_3 activehdl/axi_protocol_checker_v2_0_3
vmap axi_vip_v1_1_3 activehdl/axi_vip_v1_1_3
vmap processing_system7_vip_v1_0_5 activehdl/processing_system7_vip_v1_0_5
vmap xlconstant_v1_1_5 activehdl/xlconstant_v1_1_5
vmap lib_cdc_v1_0_2 activehdl/lib_cdc_v1_0_2
vmap proc_sys_reset_v5_0_12 activehdl/proc_sys_reset_v5_0_12
vmap axi_lite_ipif_v3_0_4 activehdl/axi_lite_ipif_v3_0_4
vmap interrupt_control_v3_1_4 activehdl/interrupt_control_v3_1_4
vmap axi_gpio_v2_0_19 activehdl/axi_gpio_v2_0_19
vmap gigantic_mux activehdl/gigantic_mux
vmap xlconcat_v2_1_1 activehdl/xlconcat_v2_1_1

vlog -work xilinx_vip  -sv2k12 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93 \
"C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work axi_infrastructure_v1_1_0  -v2k5 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/sc_util_v1_0_vl_rfs.sv" \

vlog -work axi_protocol_checker_v2_0_3  -sv2k12 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/03a9/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \

vlog -work axi_vip_v1_1_3  -sv2k12 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/b9a8/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work processing_system7_vip_v1_0_5  -sv2k12 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_processing_system7_0_0/sim/ILA_Trigger_processing_system7_0_0.v" \

vcom -work xil_defaultlib -93 \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ce49/hdl/AXITrigger_v1_0_S00_AXI.vhd" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ce49/hdl/AXITrigger_v1_0.vhd" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_AXITrigger_0_0/sim/ILA_Trigger_AXITrigger_0_0.vhd" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5160/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_10/sim/bd_f1c4_s00a2s_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/acc2/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_16/sim/bd_f1c4_m00s2a_0.sv" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_23/sim/bd_f1c4_m01s2a_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/28cb/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_29/sim/bd_f1c4_m01e_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_24/sim/bd_f1c4_m01arn_0.sv" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_25/sim/bd_f1c4_m01rn_0.sv" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_26/sim/bd_f1c4_m01awn_0.sv" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_27/sim/bd_f1c4_m01wn_0.sv" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_28/sim/bd_f1c4_m01bn_0.sv" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_22/sim/bd_f1c4_m00e_0.sv" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_17/sim/bd_f1c4_m00arn_0.sv" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_18/sim/bd_f1c4_m00rn_0.sv" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_19/sim/bd_f1c4_m00awn_0.sv" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_20/sim/bd_f1c4_m00wn_0.sv" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_21/sim/bd_f1c4_m00bn_0.sv" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_11/sim/bd_f1c4_sarn_0.sv" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_12/sim/bd_f1c4_srn_0.sv" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_13/sim/bd_f1c4_sawn_0.sv" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_14/sim/bd_f1c4_swn_0.sv" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_15/sim/bd_f1c4_sbn_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/afa8/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_7/sim/bd_f1c4_s00mmu_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/4521/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_8/sim/bd_f1c4_s00tr_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/d1fc/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_9/sim/bd_f1c4_s00sic_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/4e7b/hdl/sc_switchboard_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_2/sim/bd_f1c4_arsw_0.sv" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_3/sim/bd_f1c4_rsw_0.sv" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_4/sim/bd_f1c4_awsw_0.sv" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_5/sim/bd_f1c4_wsw_0.sv" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_6/sim/bd_f1c4_bsw_0.sv" \

vlog -work xlconstant_v1_1_5  -v2k5 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f1c3/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_0/sim/bd_f1c4_one_0.v" \

vcom -work lib_cdc_v1_0_2 -93 \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work proc_sys_reset_v5_0_12 -93 \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/ip/ip_1/sim/bd_f1c4_psr_aclk_0.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/bd_0/sim/bd_f1c4.v" \

vcom -work xil_defaultlib -93 \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_smc_0/sim/ILA_Trigger_axi_smc_0.vhd" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_rst_ps7_0_100M_0/sim/ILA_Trigger_rst_ps7_0_100M_0.vhd" \

vcom -work axi_lite_ipif_v3_0_4 -93 \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \

vcom -work interrupt_control_v3_1_4 -93 \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/8e66/hdl/interrupt_control_v3_1_vh_rfs.vhd" \

vcom -work axi_gpio_v2_0_19 -93 \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/c193/hdl/axi_gpio_v2_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_axi_gpio_0_0/sim/ILA_Trigger_axi_gpio_0_0.vhd" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/sim/bd_deaa.vhd" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_0/sim/bd_deaa_ila_lib_0.vhd" \

vlog -work gigantic_mux  -v2k5 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/d322/hdl/gigantic_mux_v1_0_cntr.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_1/bd_deaa_g_inst_0_gigantic_mux.v" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_1/sim/bd_deaa_g_inst_0.v" \

vlog -work xlconcat_v2_1_1  -v2k5 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_2/sim/bd_deaa_slot_0_aw_0.v" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_3/sim/bd_deaa_slot_0_w_0.v" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_4/sim/bd_deaa_slot_0_b_0.v" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_5/sim/bd_deaa_slot_0_ar_0.v" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/bd_0/ip/ip_6/sim/bd_deaa_slot_0_r_0.v" \

vcom -work xil_defaultlib -93 \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_system_ila_0_0/sim/ILA_Trigger_system_ila_0_0.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/ec67/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/5bb9/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/70fd/hdl" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/f90c/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/6180/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/a08d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0a8d/hdl/verilog" "+incdir+../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ipshared/0000/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/ip/ILA_Trigger_xlconstant_0_0/sim/ILA_Trigger_xlconstant_0_0.v" \

vcom -work xil_defaultlib -93 \
"../../../../ILA_Trigger.srcs/sources_1/bd/ILA_Trigger/sim/ILA_Trigger.vhd" \

vlog -work xil_defaultlib \
"glbl.v"

