set_property PACKAGE_PIN M14 [get_ports led1]
set_property PACKAGE_PIN M15 [get_ports led2]
set_property PACKAGE_PIN G14 [get_ports led3]
set_property PACKAGE_PIN D18 [get_ports led4]
set_property PACKAGE_PIN L16 [get_ports sys_clock]
set_property PACKAGE_PIN R18 [get_ports reset_rtl]
set_property IOSTANDARD LVCMOS33 [get_ports led1]
set_property IOSTANDARD LVCMOS33 [get_ports led2]
set_property IOSTANDARD LVCMOS33 [get_ports led3]
set_property IOSTANDARD LVCMOS33 [get_ports led4]
set_property IOSTANDARD LVCMOS33 [get_ports reset_rtl]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clock]

