# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/ILA_Latency/ILA_Latency.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Latency || ORIG_REF_NAME==ILA_Latency} -quiet] -quiet

# IP: bd/ILA_Latency/ip/ILA_Latency_clk_wiz_0_0/ILA_Latency_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Latency_clk_wiz_0_0 || ORIG_REF_NAME==ILA_Latency_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ILA_Latency/ip/ILA_Latency_ila_0_0/ILA_Latency_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Latency_ila_0_0 || ORIG_REF_NAME==ILA_Latency_ila_0_0} -quiet] -quiet

# IP: bd/ILA_Latency/ip/ILA_Latency_c_counter_binary_1_0/ILA_Latency_c_counter_binary_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Latency_c_counter_binary_1_0 || ORIG_REF_NAME==ILA_Latency_c_counter_binary_1_0} -quiet] -quiet

# IP: bd/ILA_Latency/ip/ILA_Latency_ila_1_0/ILA_Latency_ila_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Latency_ila_1_0 || ORIG_REF_NAME==ILA_Latency_ila_1_0} -quiet] -quiet

# IP: bd/ILA_Latency/ip/ILA_Latency_util_vector_logic_0_0/ILA_Latency_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Latency_util_vector_logic_0_0 || ORIG_REF_NAME==ILA_Latency_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/ILA_Latency/ip/ILA_Latency_pulse_rise_fall_0_0/ILA_Latency_pulse_rise_fall_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Latency_pulse_rise_fall_0_0 || ORIG_REF_NAME==ILA_Latency_pulse_rise_fall_0_0} -quiet] -quiet

# XDC: bd/ILA_Latency/ILA_Latency_ooc.xdc
